<?xml version="1.0" encoding="UTF-8" ?>
<testsuites>
  <testsuite errors="2" failures="3" hostname="DESKTOP-16O0SVF" id="0" name="DemoTestRun1" package="junit" skipped="0" tests="5" time="0.143" timestamp="2018-06-07T06:22:50">

      <testcase classname="junit.TestRun" name="Test1" time="0.008">
	  <failure message="Phone was turned off" type="junit.framework.AssertionFailedError">
Phone was turned off
</failure>
      </testcase>
	  <testcase classname="junit.TestRun" name="Test2" time="0.008">
	  <failure message="Phone was turned off" type="junit.framework.AssertionFailedError">
Phone was turned off
</failure>
      </testcase>
	  <testcase classname="junit.TestRun" name="Test3" time="0.008">
	  	  <failure message="Phone was turned off" type="junit.framework.AssertionFailedError">
Phone was turned off
</failure>

      </testcase>
	  <testcase classname="junit.TestRun" name="Test4" time="0.008">
	  	  <error message="Phone was turned off" type="java.lang.Exception">
Phone was turned off
</error>

      </testcase>
	  <testcase classname="junit.TestRun" name="Test5" time="0.008">

	  <error message="Real Defect" type="java.lang.Exception">
java.lang.Exception: No runnable methods at java.lang.reflect.Constructor.newInstance(Unknown Source) at java.lang.reflect.Constructor.newInstance(Unknown Source) at org.eclipse.ant.internal.launching.remote.EclipseDefaultExecutor.executeTargets(EclipseDefaultExecutor.java:36) at org.eclipse.ant.internal.launching.remote.InternalAntRunner.run(InternalAntRunner.java:460) at org.eclipse.ant.internal.launching.remote.InternalAntRunner.main(InternalAntRunner.java:142)
</error>
      </testcase>
	  <testcase classname="junit.TestRun" name="Test4" time="0.008">
      </testcase>

  </testsuite>
</testsuites>

